### ISSUE TITLE
Fails to render emoji and can't handle overflow words

### ISSUE THREAD

**Issue by Ir1d** [nwtgck/gh-card#1]
![image](https://user-images.githubusercontent.com/10709657/59492027-94061a80-8eba-11e9-90c6-4e7cb30351c3.png)

FYI: `24OI/OI-wiki`

**Comment by nwtgck** [comment]
Thanks!

## Links
* <https://www.webfx.com/tools/emoji-cheat-sheet>

**Comment by nwtgck** [comment]
@Ir1d Now it's available! Try this: https://gh-card.dev/repos/24OI/OI-wiki.svg.
