### ISSUE TITLE
Doesn't work for one of my repositories

### ISSUE THREAD

**Issue by jrwrigh** [nwtgck/gh-card#155]
For some reason, the svg for [jrwrigh/ANSYS_CFX](https://github.com/jrwrigh/ANSYS_CFX) doesn't work correctly. On my website, it just sits there and tries to load an image, but it doesn't work and comes up with a broken image.

When trying to create a badge on the website ([gh-card.dev](https://gh-card.dev/)), the preview image never loads. Not sure what's going on here, because it was definitely working a few weeks ago. And it works perfectly fine for all my other repositories.

**Comment by nwtgck** [comment]
@jrwrigh Thank you for reporting. I'll investigate, but it may take time.

**Comment by jrwrigh** [comment]
I think the issue is that [jrwrigh/ANSYS_CFX](https://github.com/jrwrigh/ANSYS_CFX) doesn't have a language attached to it. The gh-card generator fails for creating a card for this repository too, which doesn't have a language attached to it: https://github.com/Pratitya/wuhan2020-timeline

**Comment by nwtgck** [comment]
@jrwrigh Thank you very much for your report. I'll allow gh-card to have non-language.

**Comment by nwtgck** [comment]
I fixed this issue in 35304a3d64f0c92b42fa93644e7f26c31239b0f2. Please wait for the release.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/10933561/78845308-2deb1500-7a43-11ea-9a66-ac6efe037809.png">

**Comment by nwtgck** [comment]
@jrwrigh I released the fixed version. Thanks for your reporting.

**Comment by jrwrigh** [comment]
Welcome. Thanks for fixing it so quickly!

**Comment by nwtgck** [comment]
@jrwrigh Because of you, you found the cause!
