### ISSUE TITLE
Seems to not working on some repository

### ISSUE THREAD

**Issue by Freyskeyd** [nwtgck/gh-card#226]
Hello!

I tried to use gh-card on some of my repository but it doesn't work for som of them. (it work for the first one but no more)

the repository is Freyskeyd/instagram

I've no other information sorry :x

**Comment by nwtgck** [comment]
@Freyskeyd Sorry for my late reply. (I noticed just now...) I'll investigate this issue.

**Comment by nwtgck** [comment]
@Freyskeyd I have the following image generated by this project. Could you tell me what problem is?
<img width="516" alt="image" src="https://user-images.githubusercontent.com/10933561/83075687-3bba2f80-a0af-11ea-9386-f3d4f98704cf.png">

**Comment by Freyskeyd** [comment]
@nwtgck Yes because I add a repository description

check this PR https://github.com/nwtgck/gh-card/pull/227
