### ISSUE TITLE
Add link to SVG

### ISSUE THREAD

**Issue by trishmapow** [nwtgck/gh-card#4]
Just noticed the SVG text for the repo doesn't have a link to Github. This can be done easily with `<a>` tags after the 'repo name' comment.

example with my repo:
`<a href="https://github.com/trishmapow">
<text xmlns="http://www.w3.org/2000/svg" fill="#0366d6" fill-opacity="1" stroke="none" xml:space="preserve" x="41" y="33" font-family="sans-serif" font-size="16" font-weight="630" font-style="normal">trishmapow/rf-jam-replay</text>
</a>`

Output (clickable): https://svgshare.com/i/D_M.svg

**Comment by nwtgck** [comment]
@trishmapow Great idea!

The stars and forks may also have links like GitHub official do.

**Comment by nwtgck** [comment]
@trishmapow Now link feature is available

https://gh-card.dev/repos/trishmapow/rf-jam-replay.svg

![trishmapow/rf-jam-replay - GitHub](https://gh-card.dev/repos/trishmapow/rf-jam-replay.svg)
