### ISSUE TITLE
Is the service down ?

### ISSUE THREAD

**Issue by nvuillam** [nwtgck/gh-card#590]
I noticed GH cards do not work anymore in Mega-Linter documentation

It seems it does not work on gh-card homepage example

https://gh-card.dev/

![image](https://user-images.githubusercontent.com/17500430/129186138-2830ab79-929f-46a5-acbf-6ea5f47b0e33.png)

**Comment by hachi8833** [comment]
I got the same issue. I like the service and hope this'd be fixed soon.

**Comment by peaceiris** [comment]
I have sent this issue to the code owner via DM.

Perhaps, the following maintenance is related to this down.

- [Sunsetting API Authentication via Query Parameters, and the OAuth Applications API | GitHub Changelog](https://github.blog/changelog/2021-04-19-sunsetting-api-authentication-via-query-parameters-and-the-oauth-applications-api/)

> ## Deprecation timeline
>
> ### Brownouts
>
> During a brownout, authentication using query parameters will temporarily fail. The goal is to trigger alerts (assuming there are any) on our customers' services to help them find unmigrated authentication calls.
>
> The brownouts are scheduled for:
>
> - May 5, 2021: For 12 hours starting at 14:00 UTC
> - June 9, 2021: For 24 hours starting at 14:00 UTC
> - August 11, 2021: For 48 hours starting at 14:00 UTC
>
> [Deprecating API authentication through query parameters | GitHub Developer Guide](https://developer.github.com/changes/2020-02-10-deprecating-auth-through-query-param/)

**Comment by nwtgck** [comment]
Thank you for the reporting.

Time solved the problem (I did nothing, but solved). I will adjust the caching time to return  repo images even if GitHub is down.

**Comment by peaceiris** [comment]
I have opened #591.
