### ISSUE TITLE
The service seems to have stopped.

### ISSUE THREAD

**Issue by kojix2** [nwtgck/gh-card#592]
Thank you for creating a great service. 
I like gh-card.
It seems that the service is currently stopped. Could you please restore it?

**Comment by peaceiris** [comment]
We need to fix #591

**Comment by nwtgck** [comment]
@kojix2 @peaceiris 

Thank you for the report. I confirmed the service works now, but I did nothing.

**Comment by peaceiris** [comment]
@nwtgck Could you try a new repo? An image of a new repository will not be generated, I think.

**Comment by nwtgck** [comment]
Now, rate limit reached...

```
 GitHub API error: {"status":403,"resText":"{\"message\":\"API rate limit exceeded for...
```

**Comment by nwtgck** [comment]
I see. we have to solve #591...

**Comment by shufo** [comment]
Thank you for creating a nice service.
I use this service on my blog.

Now when I try to output it, I got Cloudflare's Bad Gateway.

![image](https://user-images.githubusercontent.com/1641039/176322423-dbf39f03-b0e7-4a26-bfb3-42d6232f529d.png)

Not all repositories seem to have the error.

OK: https://gh-card.dev/repos/nwtgck/piping-server.svg
NG: https://gh-card.dev/repos/managementtechniksysteme/quokka.svg

**Comment by nwtgck** [comment]
@shufo Thanks for the report! It is available now.

**Comment by shufo** [comment]
@nwtgck 
Thanks for the quick response!
really appreciate it.
