### ISSUE TITLE
Consider OSS License

### ISSUE THREAD

**Issue by thisBrian** [nwtgck/gh-card#6]
Love the idea, quite a cool project.
Would it be possible to add an [open source license](https://choosealicense.com/licenses/)?
Cheers

**Comment by YellowberryHN** [comment]
I second this idea. I would recommend a permissive-type license, such at the MIT, zlib or BSD license.

**Comment by nwtgck** [comment]
@thisBrian, @YellowberryHN Thanks! Now it has a [license](https://github.com/nwtgck/gh-card/blob/develop/LICENSE).
